server:
  port: 2222

spring:
  profiles:
    active: prod
  application:
    name: rempms-notification-service
  cloud:
    openfeign:
      okhttp:
        enabled: true
    stream:
      bindings:
        informRegistration-in-0:
          destination: inform-registration
          group: ${spring.application.name}
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092

logging:
  level:
    org:
      springframework:
        cloud: DEBUG