spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rempms_notification_management
    username: postgres
    password: rempmsdev@123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

feign:
  client:
    config:
      rempms-message-service:
        url: http://localhost:2991

email:
  retry:
    count: 3