server:
  port: 2998

spring:
  profiles:
    active: prod
  application:
    name: rempms-notification-service

  cloud:
    openfeign:
      okhttp:
        enabled: true

    function:
      definition: email
    stream:
      default:
        content-type: application/json
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9094
          autoCreateTopics: true
      bindings:
        email-in-0:
          destination: user-registration-email,email-verification-url,candidate-registration-email
          group: ${spring.application.name}-email
#        email-out-0:
#          destination: user-registration-email-response

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true

email:
  retry:
    count: 3

logging:
  level:
    org:
      springframework:
        cloud: DEBUG